name: hsma_datix_hackathon2
channels:
  - conda-forge
dependencies:
  - python=3.11.9
  - pip
  - pip:
    - pandas==2.2.2
    - numpy==1.26.4
    - matplotlib==3.9.1.post1
    - plotly==5.23.0
    - streamlit==1.37.0
    - ipykernel==6.29.5
    - ipython==8.27.0
    - wordcloud==1.9.3
    - openpyxl
    - nbformat>=4.2.0
    - scikit-learn==1.4.2
    - seaborn

